### ISSUE TITLE
(번외) 깃헙 이슈 + 프로젝트 꿀팁

### ISSUE THREAD

**Issue by mikonu** [mikonu/fastcampus-project-board#13]
깃업 이슈와 깃헙 프로젝트를 다룰 때 사용하는 세부 기능을 알아본다.

## Todo

* [x] 이슈 레이블
* [x] 마일스톤
* [x] 프로젝트 보드의 옵션 수정
    * 레이블과 연관 pr이 표시되게끔 수정하기
* [x] 프로젝트 자동화 부분 파악: workflow
* [x] 프로젝트 커스텀 필드

**Comment by mikonu** [comment]
강의 설명 마치고 이슈 종료.
