### ISSUE TITLE
게시판 서비스 뷰 만들기

### ISSUE THREAD

**Issue by mikonu** [mikonu/fastcampus-project-board#15]
눈에 보이는 게시판 그림이 있으면 개발의 방향을 느끼기가 더 수월할 것 같다.
이에 게시판 서비스 뷰를 만들기 위해 해야 할 일을 정리하고, 실행한다.
여기서는 눈에 보이는 부분에 집중하고, 세부 기능 구현은 별도로 한다.

## Todo

* [x] 뷰 엔드포인트 테스트 정의
* [x] 뷰 구현
* [x] 게시판 페이지 만들기
* [x] 게시글 페이지 만들기
* [x] 로그인 페이지 만들기
* [x] 뷰에 디자인 붙이기

## Reference

* https://getbootstrap.com/
* https://gist.github.com/djkeh/6e1d557ce8c466135b1541d342b1c25c
* https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#decoupled-template-logic
* https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#fragments
* https://developer.mozilla.org/en-US/docs/Glossary/Semantics#semantic_elements
* https://www.w3schools.com/html/html5_semantic_elements.asp
* https://csszengarden.com/
