### ISSUE TITLE
뷰 기능 정의

### ISSUE THREAD

**Issue by mikonu** [mikonu/fastcampus-project-board#19]
뷰 구현을 위한 기능을 테스트로 먼저 정의한다.

## Todo

* [x] 게시판 페이지 기능 테스트 정의
* [x] 게시글 페이지 기능 테스트 정의
* [x] ~~로그인 페이지 기능 테스트 정의~~
* [x] 메인 페이지 -> 게시판 페이지로 포워딩
    * 포워딩 vs. 리다이렉션

## Reference

* https://martinfowler.com/bliki/TestDouble.html
* https://martinfowler.com/articles/mocksArentStubs.html
