### ISSUE TITLE
뷰 기능 구현

### ISSUE THREAD

**Issue by mikonu** [mikonu/fastcampus-project-board#20]
#19 작업을 토대로 실제 기능을 명세(테스트)에 맞춰 구현한다.

## Todo

* [x] 게시판 페이지 (조회) 기능 구현
* [x] 게시글 페이지 (조회) 기능 구현
* [x] ~~로그인 페이지 기능 구현~~ -> 스프링 시큐리티로 구현됨
