### ISSUE TITLE
데이터베이스 접근 로직 테스트 정의

### ISSUE THREAD

**Issue by mikonu** [mikonu/fastcampus-project-board#5]
프로젝트가 #3 에서 설계한 도메인 정보에 따라 DB에 접근하고 데이터를 다룰 수 있도록 준비를 마치고, 테스트로 동작 여부를 확인한다.

## Todo

* [x] spring data jpa 및 사용할 db 드라이버 의존성 추가
* [x] jpa auditing 기능 활성화
* [x] 도메인 클래스를 엔티티 클래스로 바꾸기
    * `@Entity` 및 각종 엔티티 연관 애노테이션
    * 연관관계 매핑
    * 생성자 설계
    * `equals()`, `hashcode()` 작성 요령
    * getter/setter 패턴과 롬복의 적용
* [x] DB에 접근할 수 있도록 repository 인터페이스 만들기
* [x] 애플리케이션 프로퍼티 설정하기 -> yaml 파일로 작성하기
* [x] 테스트용 데이터 준비하기
* [x] jpa 테스트: `@DataJpaTest`

## Reference

* https://spring.io/guides/gs/accessing-data-jpa
* https://thorben-janssen.com/ultimate-guide-to-implementing-equals-and-hashcode-with-hibernate/#Using_a_Generated_Primary_Key
* https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/
* https://jpa-buddy.com/blog/hopefully-the-final-article-about-equals-and-hashcode-for-jpa-entities-with-db-generated-ids/
