### ISSUE TITLE
게시판 api 만들기

### ISSUE THREAD

**Issue by mikonu** [mikonu/fastcampus-project-board#8]
게시글, 댓글 데이터를 조작하는 기능을 제공하기 위한 API가 필요하다.
이 기능은 다른 시스템에서 게시판 서비스 컨텐츠를 제어하는데 활용할 수 있을 것이다. (예: 어드민, 제휴사 접근 등)
간편하게 Spring Data REST를 활용하여 구현하고, 해당 api 들의 존재 여부만 체크하는 통합테스트를 작성해보자.

## Todo

* [x] spring data rest 의존성 추가
* [x] 관련 애플리케이션 프로퍼티 설정
* [x] 테스트 작성
* [x] querydsl 지원을 활용하여 API에 검색 기능 부여하기 (`QuerydslPredicateExecutor`, `QuerydslBinderCustomizer`)
