### ISSUE TITLE
계정 도메인 추가 작업

### ISSUE THREAD

**Issue by mikonu** [mikonu/fastcampus-project-board#9]
#3 에서 작업하지 않은 회원 계정 도메인을 추가로 설계한다.
게시판 서비스는 인증 기능을 제공해야 하므로, 회원 정보를 관리할 필요가 있다.

## Todo

* [x] 회원 계정 도메인 엔티티 설계
* [x] 회원 저장소 인터페이스 작성
* [x] 테스트용 계정을 테스트 데이터에 추가
* [ ] (optional) 회원 정보의 data rest 노출 여부를 고민하여 테스트에 반영하기
